function createSlidersAndButtons
%UNTITLED7 Summary of this function goes here
%   Detailed explanation goes here
sld1 = uicontrol('Style', 'slider',...
    'Min',-5,'Max',5,'Value',0,...
    'Position', [450 20 80 20],...
    'Callback', @xr_z); 
txt1 = uicontrol('Style','text',...
    'Position',[525 20 40 20],...
    'String','ZVal');

sld2 = uicontrol('Style', 'slider',...
    'Min',-5,'Max',5,'Value',0,...
    'Position', [450 50 80 20],...
    'Callback', @xr_y); 
txt2 = uicontrol('Style','text',...
    'Position',[525 50 40 20],...
    'String','YVal');

sld3 = uicontrol('Style', 'slider',...
    'Min',-5,'Max',5,'Value',0,...
    'Position', [450 80 80 20],...
    'Callback', @xr_x); 
txt3 = uicontrol('Style','text',...
    'Position',[525 80 40 20],...
    'String','XVal');
btn = uicontrol('Style', 'pushbutton', 'String', 'Disamb',...
    'Position', [20 40 120 20],...
    'Callback', @set_rob_pos);       

btn = uicontrol('Style', 'pushbutton', 'String', 'Resample Goals',...
    'Position', [20 10 150 20],...
    'Callback', @set_goal_pos);   

popup = uicontrol('Style', 'popup',...
           'String', {'2','3','4','5','6'},...
           'Position', [20 340 100 50],...
           'Callback', @set_num_goals); 
txt3 = uicontrol('Style','text',...
    'Position',[20 390 100 20],...
    'String','NumGoals');
end

